root: ./

redirects:
  start.md: home.md
  combining.md: Collections/combining-collections.md
  faq-and-known-issues.md: Guides/troubleshooting.md
  install.md: Installation/Vortex/installation.md
  keybinds.md: "Collections/Stardew Valley VERY Expanded/keybinds-controllers.md"
  manual-install.md: Installation/manual.md
  personalization.md: Guides/personalization.md
  troubleshooting.md: Guides/troubleshooting.md
  "Installation/Vortex/faq.md": Installation/Vortex/troubleshooting.md
  "Installation/NMA/installation.md": Installation/nma.md
  "Installation/NMA/faq.md": Installation/nma.md
  "Installation/NMA/README.md": Installation/nma.md
  "Installation/Stardrop/installation.md": Installation/stardrop.md
  "Installation/Stardrop/faq.md": Installation/stardrop.md
  "Installation/Stardrop/README.md": Installation/stardrop.md
  "Installation/Stardrop/transfer-to-stardrop.md": Installation/stardrop.md
  "Installation/Manual/installation.md": Installation/manual.md
  "Installation/Manual/faq.md": Installation/manual.md
  "Installation/Manual/README.md": Installation/manual.md
  "Getting Started/getting-started.md": home.md
  "Getting Started/faq-known-issues.md": Guides/troubleshooting.md
  "Getting Started/updating-collections.md": Guides/updating-collections.md
  "Collections/Aesthetic Valley/overview.md": Collections/aesthetic-valley.md
  "Collections/Aesthetic Valley/keybinds-controllers.md": Collections/aesthetic-valley.md
  "Collections/Aesthetic Valley/README.md": Collections/aesthetic-valley.md
  "Collections/Stardew Valley VERY Expanded/overview.md": "Collections/Stardew Valley VERY Expanded/README.md"

