root: ./

redirects:
  combining.md: Collections/combining-collections.md
  faq-and-known-issues.md: faq-known-issues.md
  install.md: Installation/Vortex/installation.md
  keybinds.md: Collections/Stardew Valley VERY Expanded/keybinds-controllers.md
  manual-install.md: Installation/Manual/installation.md
  personalization.md: Guides/personalization.md
  troubleshooting.md: Guides/troubleshooting.md

