root: ./
structure:
  readme: index.md

redirects:
  start.md: index.md
  home.md: index.md
  combining.md: Installation/multiple-collections.md
  faq-and-known-issues.md: Troubleshooting/index.md
  install.md: Installation/index.md
  keybinds.md: "Collections/Stardew Valley VERY Expanded/keybinds-controllers.md"
  manual-install.md: Installation/manual.md
  personalization.md: Customization/index.md
  troubleshooting.md: Troubleshooting/index.md
  "Guides/troubleshooting.md": Troubleshooting/index.md
  "Guides/updating-collections.md": Updating/index.md
  "Guides/personalization.md": Customization/index.md
  "Guides/how-to-create-a-collection.md": Customization/creating-collections.md
  "Collections/combining-collections.md": Installation/multiple-collections.md
  "Installation/Vortex/installation.md": Installation/index.md
  "Installation/Vortex/troubleshooting.md": Troubleshooting/vortex-troubleshooting.md
  "Installation/Vortex/faq.md": Troubleshooting/vortex-troubleshooting.md
  "mod-managers/vortex/troubleshooting.md": Troubleshooting/vortex-troubleshooting.md
  "mod-managers/vortex/installation.md": Installation/index.md
  "mod-managers/vortex/updating-collections.md": Updating/index.md
  "mod-managers/vortex/faq.md": Troubleshooting/vortex-troubleshooting.md
  "mod-managers/overview.md": index.md
  "mod-managers/nexus-mods-app.md": index.md
  "Installation/Stardrop/installation.md": Installation/stardrop.md
  "Installation/Stardrop/faq.md": Installation/stardrop.md
  "Installation/Stardrop/README.md": Installation/stardrop.md
  "Installation/Stardrop/transfer-to-stardrop.md": Installation/stardrop.md
  "Installation/Manual/installation.md": Installation/manual.md
  "Installation/Manual/faq.md": Installation/manual.md
  "Installation/Manual/README.md": Installation/manual.md
  "Getting Started/getting-started.md": index.md
  "Getting Started/faq-known-issues.md": Troubleshooting/index.md
  "Getting Started/updating-collections.md": Updating/index.md
  "Collections/Aesthetic Valley/overview.md": Collections/aesthetic-valley.md
  "Collections/Aesthetic Valley/keybinds-controllers.md": Collections/aesthetic-valley.md
  "Collections/Aesthetic Valley/README.md": Collections/aesthetic-valley.md
  "Collections/Stardew Valley VERY Expanded/overview.md": About/index.md
  "Collections/Stardew Valley VERY Expanded/README.md": About/index.md
  "Collections/aesthetic-valley-collections.md": About/index.md
